name: Repo Resources Sync
description: Sync resources from/to dedicated branch

inputs:
  resources-branch:
    description: Test resource branch
    default: test_resource
    required: true
  resource-name:
    description: Test resource title
    required: true
  target-path:
    description: Path to folder
    required: true
  github-token:
    description: Github token. With permissions to read-write in repository
    required: true

runs:
  using: node20
  main: dist/main.js
  post: dist/post.js